default:
    image: ubuntu:bionic

stages:
    - lint
    - build
    - test

# Templates
.before_script_build: &before_script_build
    before_script:
        # Packages
        - apt-get update
        - apt-get install -y gcc-7 g++-7 make cmake git
        # Use CI token to fetch git submodules
        - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf
                                  "git@gitlab.com:"
        - git submodule update --init --recursive
        # Environment variables
        - export CC=gcc-7 CXX=g++-7 BUILD_TESTS=ON INSTALL_PREFIX=.

.before_script_test: &before_script_test
    before_script:
        - apt-get update
        - apt-get install -y make g++-7 valgrind
        - export LD_LIBRARY_PATH=build/lib

.artifacts_build: &artifacts_build
    artifacts:
        paths:
            - build/tests/test_*
            - build/lib/*.so
        expire_in: 1 hrs

# Lint step
lint:
    stage: lint
    before_script:
        - apt-get update
        - apt-get install -y clang-format-9
    script:
        - tools/clang_format.sh --clang-format-bin clang-format-9

# Build step
build:release:
    stage: build
    <<: *before_script_build
    script:
        - make install BUILD_TYPE=Release BUILD_EXAMPLES=ON -j$(nproc)
    <<: *artifacts_build

build:asan:
    stage: build
    <<: *before_script_build
    script:
        - make install ENABLE_ASAN=ON -j$(nproc)
    <<: *artifacts_build

build:usan:
    stage: build
    <<: *before_script_build
    script:
        - make install ENABLE_USAN=ON -j$(nproc)
    <<: *artifacts_build

build:tsan:
    stage: build
    <<: *before_script_build
    script:
        - make install ENABLE_TSAN=ON -j$(nproc)
    <<: *artifacts_build

# Test step
test:release:
    stage: test
    needs: ["build:release"]
    dependencies:
        - build:release
    <<: *before_script_test
    script:
        - make test

test:valgrind:
    stage: test
    needs: ["build:release"]
    dependencies:
        - build:release
    <<: *before_script_test
    script:
        - make test_valgrind

test:asan:
    stage: test
    needs: ["build:asan"]
    dependencies:
        - build:asan
    <<: *before_script_test
    script:
        - make test

test:usan:
    stage: test
    needs: ["build:usan"]
    dependencies:
        - build:usan
    <<: *before_script_test
    script:
        - make test

test:tsan:
    stage: test
    needs: ["build:tsan"]
    dependencies:
        - build:tsan
    <<: *before_script_test
    script:
        - make test
